# Generated by Django 4.1.4 on 2022-12-21 19:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('games', models.TextField(verbose_name='Текст')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('picture', models.ImageField(upload_to='images/')),
                ('category_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
