# Generated by Django 4.1.4 on 2022-12-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_games_delete_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='games',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Существует'),
        ),
        migrations.AddField(
            model_name='games',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='Цена'),
        ),
    ]
